# Generated by Django 4.2.2 on 2023-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
