# Generated by Django 4.2.2 on 2023-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0004_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
