# Generated by Django 4.2.2 on 2023-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0005_alter_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pais',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
