# Generated by Django 4.2.2 on 2023-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0006_blog_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
