# Generated by Django 4.2.2 on 2023-07-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0007_alter_blog_options_alter_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
